### PR TITLE
Support for Victoria 1.8.x

### PR DESCRIPTION
**Pull request by kaiser-chris**
Hi @tboby and @CaesarVincens,

I am currently working on fully supporting Victoria 1.8.x

This is a huge amount of changes and seeing as my last pull request broke the official CWT tools this pull request should be tested and debugged on the VSCode plugin before merging.

I am using IntelliJ and the [Paradox Language Support](https://plugins.jetbrains.com/plugin/16825-paradox-language-support) plugin by @DragonKnightOfBreeze.

### CODE REVIEW

**Comment by kaiser-chris** [comment]
@tboby and @CaesarVincens,

this pull request is ready but my changes produce problems with the VSCode plugin.

Can you maybe look into this because this looks like an error with the plugin itself.
As far as I can tell everything I used in the CWT files is valid.

**Comment by tboby** [comment]
image
image

cwt files don't support parens in keys like that, so it's falling over on links.cwt which is done first before anything else :)

**Comment by kaiser-chris** [comment]
Hmm this works in intellij but in the end it is a hack to just pass parsing of base game files.
But for now I will remove those from the pull request.

I think a CWT extension is needed here:

In Victoria 3 scripts you can use a link to get values.

This gets the number of trade route levels with another country:
`num_mutual_trade_route_levels_with_country(root)`

This gets the relations number between the in scope country and actor:
`relations(scope:actor)`

This format is also used in Victoria 3 scripts, which seems to be the same as above:
`relations:root`

to define something like this in links would need something like:
```
relations($var$) = {
    input_var_scopes = country
    input_scopes = country
    output_scope = value
    type = value
}
```

**Comment by tboby** [comment]
Formula is immediately recursive. If you want to recuse you need to go through a "group" alias (like triggers).
single_alias is done by direct find and replace, so it makes an infinitely big rules file :)
normal alias is done by checking a list at runtime, so recursion is fine

**Comment by kaiser-chris** [comment]
Thank you for looking into this.
Can you try my latest changes one more time?

If this is not it I will look into this tomorrow when I got more time.

**Comment by tboby** [comment]
Yup, that makes the rules load again.
There are a few dozen issues being flagged by the rules parsing engine, but it always takes a while to get through all those.

Shall we merge this for now?

**Comment by kaiser-chris** [comment]
For me this is done if it works in your CWT Tools.

This makes all base game files in the latest game version parsable.
So in general it should be a major win for Victoria 3 support.

**Comment by tboby** [comment]
Thanks for all the work :)

**Comment by DragonKnightOfBreeze** [comment]
> Hmm this works in intellij but in the end it is a hack to just pass parsing of base game files. But for now I will remove those from the pull request.
> 
> I think a CWT extension is needed here:
> 
> In Victoria 3 scripts you can use a link to get values.
> 
> This gets the number of trade route levels with another country: `num_mutual_trade_route_levels_with_country(root)`
> 
> This gets the relations number between the in scope country and actor: `relations(scope:actor)`
> 
> This format is also used in Victoria 3 scripts, which seems to be the same as above: `relations:root`
> 
> to define something like this in links would need something like:
> 
> ```
> relations($var$) = {
>     input_var_scopes = country
>     input_scopes = country
>     output_scope = value
>     type = value
> }
> ```

Seems like PLS need a new feature update for this

**Comment by kaiser-chris** [comment]
@DragonKnightOfBreeze I created an [issue](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/issues/101) for PLS where I further refined it.

@tboby should I also create an issue for CWTools in general?

**Pull request merged**
