### PR TITLE
Major Rework

### PR DESCRIPTION
**Pull request by kaiser-chris**
Hi,

this is a major rework of the CWT files.

Some caveats:

- My goal is NOT to complete all CWTs. I just fix errors that I find when developing my own mod
  - Deprecated things are generally not removed
  - Completeness even for newly implemented effects/triggers may not be guarantueed
  - It should in general be an improvement but not the final version
- I am using IntelliJ and the [Paradox Language Support](https://plugins.jetbrains.com/plugin/16825-paradox-language-support) plugin by @DragonKnightOfBreeze
  - Changes may reflect specifics/bugs in that plugins CWT parser
    - I try to verify some things in VSCode and already found some bugs in the IntelliJ Plugin but not everything
    - https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/issues/86
    - https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/issues/85
    - https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/issues/84
  - Verification with your VSCode plugin is still needed

This pull request should also implement everything from: #10 

Regards,

Chris

EDIT: Rewrote Pull Request description to clarify some caveats with my changes.

### CODE REVIEW

**Comment by tboby** [comment]
@kaiser-chris Up to you! Larger requests means you don't have to try and get my or @CaesarVincens attention as frequently :)

Do ping me if something is ready and I haven't merged it in a while.

**Comment by kaiser-chris** [comment]
Ok then I will close this pull request for now and recreate it after I am 'finished'

**Comment by tboby** [comment]
There's a draft mode you could put it in so that others can still see it exists

**Comment by kaiser-chris** [comment]
Done

**Comment by CaesarVincens** [comment]
Many thanks for putting all this work in! I had started a bit on Vic3 back in '22, but never got much done. I'll see about putting my stuff up online in case any of it helps you.

**Comment by CaesarVincens** [comment]
> Many thanks for putting all this work in! I had started a bit on Vic3 back in '22, but never got much done. I'll see about putting my stuff up online in case any of it helps you.

Now that I look back at it, I may have already merged in all my work. Well, a good chance to check again.

**Comment by kaiser-chris** [comment]
@tboby After a long hiatus this should be good to merge.

All caveats in the original description still apply but in general it should be an improvement.

**Comment by DragonKnightOfBreeze** [comment]
Note that there are some useful options for pls, like `## file_extensions = xxx` and `## color_type = xxx`, you can find their usages in https://github.com/DragonKnightOfBreeze/cwtools-stellaris-config

**Comment by kaiser-chris** [comment]
@DragonKnightOfBreeze thank you I will look into that.

**Comment by kaiser-chris** [comment]
@DragonKnightOfBreeze @tboby does one of you know how to express references to defines?

I don't know whether other games use them like vic3 but there are defines with a Namespace and a Variable (configured in folder 'defines').
These are then referenced with the define:\<Namespace\>|\<Variable Name\>. This is done in a few vanilla locations but one notable location is in pop_types.
Below I have example code that at least allows me to link to a Namespace but I do not know how to configure the part after the pipe ( | ).

Is this a problem with the IntelliJ Plugin or a missing feature in cwt?

### common/defines/00_graphics.txt (excerpt)
```
... (more code before)
NRoutes = {
	DIRTROAD_BRIDGES = { "dirtroad_bridge_01" }
	RAILROAD_1_BRIDGES = { "railroad_bridge_01" "railroad_bridge_02" }
	BRIDGE_SIZES = {
		"_small_mesh"
		"_medium_mesh"
		"_large_mesh"
		}
	ROUTE_ENTITIES_CUTOFF = 250				# zoom at which we hide all route entities
}

NPortrait = {
	GRACEFUL_AGING_START = 25	# After this age, added life expectancy will make a character look younger than they are; the effect grows the further past this point one goes
	GRACEFUL_AGING_END = 70		# This is the apparent age at which life expectancy stops slowing down visual aging (each year onwards ages you visually 1 year)
	MAX_AGE = 100.0				# At this age portraits will use the special age gene at full strength
	PORTRAIT_MALE_ADULT_AGE = 18	# The boy -> male portrait change happens at this age
	PORTRAIT_FEMALE_ADULT_AGE = 18	# The girl -> female portrait change happens at this age
}

NProvinceHighlight = {
	TEXTURE_WIDTH = 2048
	TEXTURE_HEIGHT = 1024
	# Province highlights use poisson disc sampling to create a gradient
	# Poisson disc allows for a wider sample are with fewer samples
	KERNEL_SCALE = 8	# Size of the sample area, in world space
	SAMPLE_COUNT = 16	# How many samples to use (max 16)
}
... (more code after)
```

### common/pop_types/capitalists.txt (excerpt)
```
... (more code before)
	portrait_age = {
		integer_range = {
			min = define:NPortrait|GRACEFUL_AGING_START
			max = define:NPortrait|GRACEFUL_AGING_END
		}
	}
... (more code after)
```

### common/defines.cwt
```
types = {
    type[define] = {
        path = "game/common/defines"
    }
}

define = {

}
```

### links.cwt (Excerpt)
```
... (more code before)
	define = {
		desc = " Reference the value of a numeric define: define:Namespace|Name"
		from_data = yes
		data_source = <define>
		prefix = define:
		output_scope = value
		type = value
	}
... (more code after)
```

IDE Screenshots:
image
image

**Comment by DragonKnightOfBreeze** [comment]
Seems like there should be a new data type `$define_reference_expression` to write related cwt configs,
and PLS should provide support for this and related features in future versions.
Just like database object expression which is newly supported by PLS.

**Comment by DragonKnightOfBreeze** [comment]
Be better to make an issue for PLS in GitHub :)
It should be not very hard to implement support for this, but it still takes some time :(

**Comment by DragonKnightOfBreeze** [comment]
@kaiser-chris okay

**Pull request merged**
